config/routes.rb
Rails.application.routes.draw do
  get 'order_items/create'

  devise_for :users
  resources :users do
    resources :orders do
      get :review
    end
  end
  resources :menus, only: [:show, :index]
  resources :menu_items
  resources :order_items, only: [:create, :update, :destroy]
  root 'menus#index'
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :menu_item
  belongs_to :order

  before_save :finalize

  validates_presence_of :quantity
  validates_numericality_of :quantity, { only_integer: true, greater_than: 0 }

  def finalize
    self.total_price = quantity * unit_price
  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  def create
    @order.add_item(order_item_params)

    if @order.save!
    else
      redirect_to items_path, alert: "There was a problem adding this item to your cart."
    end
  end

  def destroy
    @order.delete_item(params)
    
    if @order.save
    else
      redirect_to items_path, alert: "There was a problem deleting this item from your order."
    end
  end

  def update
    @order.update_item(order_item_params)

    if @order.save
    else
      redirect_to items_path, alert: "There was a problem updating your order."
    end

  end

  private

  def order_item_params
    params.require(:order_item).permit(:quantity, :id, :unit_price, :menu_item_id)
  end
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/views/order_items/_order_item.html.erb
<li class="list-group-item">
    <%= order_item.menu_item.name %> $<%= '%.2f' % order_item.total_price %>
    <%= form_for( order_item, remote: true) do |f| %>
        <div class="input-group">
            <%= f.number_field :quantity, value: order_item.quantity.to_i, class: "form-control", min: 1 %>
            <%= f.hidden_field :id, value: order_item.id %>
            <span class="input-group-addon">
                <%= f.submit "Update", class: "btn btn-primary" %>
            </span>
            <span class="input-group-addon" style="padding-left: 4px;">
                <%= link_to "Delete", order_item_path(order_item), remote: true, method: :delete, data: {confirm: 'Are you sure?'},  class:"btn btn-danger"%>
            </span>
        </div>
    <% end %>
</li>

app/views/order_items/_order_item_inputs.html.erb
<% if current_user %>
    <div class="container">
        <%= form_for( @order_item, remote: true) do |f| %>
        <div class="input-group">
            <%= f.number_field :quantity, value: @order_item.quantity.to_i, class: "form-control", min: 1 %>
            <%= f.hidden_field :menu_item_id, value: menu_item.id %>
            <%= f.hidden_field :unit_price, value: menu_item.price %>
            <span class="input-group-addon"><%= f.submit "Add to order", disabled: menu_item.item.disabled?, class: button_status(menu_item.item) %></span>
        </div>
    <% end %>
    <%= link_to "Edit", edit_menu_item_path(menu_item), class:"btn btn-secondary"%>
    <%= link_to "Delete", menu_item_path(menu_item), method: :delete, data: {confirm: 'Are you sure?'},  class:"btn btn-danger"%>
    </div>
<% end %>

app/views/order_items/_order_items_list.html.erb
<% if !@order.order_items.empty? %>
    <div id="order-form" class="container">
        <ul class="list-group">
            <% @order.order_items.each do |order_item| %>
                <%= render "order_items/order_item", order_item: order_item %>
            <% end %>
            <li class="list-group-item">Order total: $<%= '%.2f' % @order.total %></li>
            <li class="list-group-item"><%= link_to "Checkout", user_order_review_path(current_user, @order), class: checkout(@order) %></li>

        </ul>
    </div>
<% else %>
    <p class="alert alert-primary">Add an item to your order to get started</p>
<% end %>

app/views/order_items/_order_items_list_final.html.erb
<% if !@order.order_items.empty? %>
    <div id="order-form" class="container">
        <ul class="list-group">
            <% @order.order_items.each do |order_item| %>
                <%= render "order_items/order_item", order_item: order_item %>
            <% end %>
            <li class="list-group-item">Order total: $<%= '%.2f' % @order.total %></li>
            <%= form_for @order, url: user_order_path(current_user, @order) do |t| %>
                <li class="list-group-item"><%= t.submit "Submit Order", class: "btn btn-primary" %></li>
            <% end  %>
        </ul>
    </div>
<% else %>
    <p class="alert alert-primary">Add an item to your order to get started</p>
<% end %>

app/views/order_items/create.js.erb
<% if @order.errors.any? %>
    alert("not valid.")
<% else %>
  $("#order-list").html("<%= escape_javascript(render 'order_items/order_items_list') %>")
<% end %>

app/views/order_items/destroy.js.erb
<% if @order.errors.any? %>
    alert("not valid.")
<% else %>
  $("#order-list-final").html("<%= escape_javascript(render 'order_items/order_items_list_final') %>")
  $("#order-list").html("<%= escape_javascript(render 'order_items/order_items_list') %>")
<% end %>

app/views/order_items/update.js.erb
<% if @order.errors.any? %>
    alert("not valid.")
<% else %>
  $("#order-list-final").html("<%= escape_javascript(render 'order_items/order_items_list_final') %>")
  $("#order-list").html("<%= escape_javascript(render 'order_items/order_items_list') %>")
<% end %>