config/routes.rb
Rails.application.routes.draw do
  get 'order_items/create'

  devise_for :users
  resources :users do
    resources :orders do
      get :review
    end
  end
  resources :menus, only: [:show, :index]
  resources :menu_items
  resources :order_items, only: [:create, :update, :destroy]
  root 'menus#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MenU</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <div class="dropdown show">
            <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Menus
            </a>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
              <% @menus.each do |menu| %>
                <%= link_to  menu.name, menu_path(menu), class: "dropdown-item" %>
              <% end %>
            </div>
        </div>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Add Item", new_menu_item_path, class: active_class('/menu_items/new') %>
        </li>
        <li class="nav-item">
          <%= link_to "Orders", user_orders_path(current_user), class: active_class('/users/' + current_user.id.to_s + '/orders') %>
        </li>
        <li class="nav-item">
          <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "nav-link") %>
        </li>
        <li class="nav-item ml-auto">
            <a class="nav-link"><%= current_user.email %></a>
        </li>
        <% else %>
        <li class="nav-item">
          <%= link_to('Login', new_user_session_path, class: active_class('/users/sign_in')) %>
        </li>
      <% end %>
    </ul>
    <%= yield %>
  </body>
</html>